#! /bin/sh
quartus_stp -t ../../EightThirtyTwo/tcl/832bridge.tcl 2>/dev/null >/dev/null &
while ! netstat -tna | grep 'LISTEN\>' | grep -q ':33581\>'; do
  sleep 1
done
../../EightThirtyTwo/832ocd/832ocd -eb -m Firmware/DebugTest.bin.map
kill $!
