all:
	make -C HelloWorld
	make -C Dhrystone
	make -C Dhrystone_Dual
	make -C Malloc
	make -C PS2Keyboard
	make -C Filesystem
	make -C Modplayer
	make -C Conway
	make -C AppHost

clean:
	-make -C HelloWorld clean
	-make -C Dhrystone clean
	-make -C Dhrystone_Dual clean
	-make -C Malloc clean
	-make -C PS2Keyboard clean
	-make -C Filesystem clean
	-make -C Modplayer clean
	-make -C Conway clean
	-make -C AppHost clean


